CHANNELS_NUMBER = 8
FILE_LOCATION = '../../../data/app/'

# GUI constants
WINDOW_X = 1600
WINDOW_Y = 800
# Graph constants
X_LIM = 200
DPI = 100
UPDATE_AXIS_INTERVAL = 3  # update y axis scale every UPDATE_AXIS_INTERVAL samples
REDRAW_INTERVAL = 4  # new frame every REDRAW_INTERVAL milliseconds
GRAPH_PROPORTION = 0.1  # set y axis as 2 * GRAPH_PROPORTION * current_value

# Experiment defaults
DEFAULT_AGE = 25
DEFAULT_ELECTRODES = "[O1, O2, FP1, FP2, C3, C4, P7, P8]"
DEFAULT_GENDER = "male"
DEFAULT_NAME_PREFIX = "rec"
DEFAULT_RECORD_DURATION = 10.
DEFAULT_SUBJECT = "patient0"
MAX_RECORD_DURATION = 280.

# Experiments options
_FLASH = 'Flash'
_EO = 'EO'
_EC = 'EC'
_SSVEP10 = 'SSVEP10'
_SSVEP20 = 'SSVEP20'
_SSVEP30 = 'SSVEP30'
_PINCODE_4_TRUE_SEQ_REP_3 = "PIN4CORR3REP"
_P300_SECRET = "P300SECRETSPELLER"

# Experiment constants
EP_EO_DURATION = 3.
EP_SSVEP_DURATION = 10.
EP_FLASH_RECORD_DURATION = 5.

FLASH_START = 2000
FLASH_END = 2100

PINCODE_FLASH_INTERVAL = 1000  # Number tile flashes every PINCODE_FLASH_INTERVAL milliseconds
PINCODE_FLASH_DURATION = 350  # Number tile dims after PINCODE_FLASH_DURATION milliseconds

